### PR TITLE
Refactor interface in spinal to handle more external magnetometer built in GPS module

### PR DESCRIPTION
**Pull request by tongtybj**
@chibi314 @kanke-hayata 

I have almost finished to implement the usage of next generation of GPS module with built-in magnetometer.
Tonight, I will attach the instruction images to show how to use and configure the new GPS, 
and also provide two prepared GPS module for your outdoor experiment (two hydrus).

### CODE REVIEW

**Comment by tongtybj** [comment]
I make three samples of following GPS module. Two of them are for @chibi314 and @kanke-hayata 
Connectors are modified and can be directly connected to  Spinal  with this branch.
iOS の画像 (2)

**Comment by tongtybj** [comment]
Important tips:

1. Connector pinout:
URAT: 5V(Orange), GND(Black), TX (White), RX (Yellow)
I2C: SCL (Red), SDA (Green)

iOS の画像 (1)

2. Configuration
I will update the description in https://github.com/JSKAerialRobot/aerial_robot/wiki/sensors.
The most important modification is to change the rate from 1000ms to 40ms:
スクリーンショット 2021-04-02 00 26 40

**Comment by tongtybj** [comment]
> The most important modification is to change the rate from 1000ms to 100ms

@chibi314  100ms, right?

**Comment by chibi314** [comment]
@tongtybj 

Yes. I set the rate to 100 ms and confirmed that hydrus could hover stable in outdoor environment.
But the relationship between the rate and the latency is not precisely evaluated.

**Comment by tongtybj** [comment]
@chibi314 

grateful for you

**Comment by tongtybj** [comment]
We need tp set measurement rate to 101ms (9,9Hz). 
Please refer to https://portal.u-blox.com/s/question/0D52p0000AOK91vCQD/can-neom9n-only-use-16-satellites-with-nav-update-rate-5hz

**Pull request merged**
